version: "3.8"

services:
  app:
    container_name: console-logbook-front-container
    image: docker.pkg.github.com/yarmsl/console.logbook/console-logbook-front
    build:
      context: .
    ports:
      - 80:3000