version: "3"

services:
  web:
    image: docker.pkg.github.com/yarmsl/console.logbook/console-logbook-front
    container_name: console-logbook-front-container
    build:
      context: .
    ports:
      - 443:443