version: "3"

services:
  app:
    image: docker.pkg.github.com/yarmsl/express-server/console-logbook-server:develop
    container_name: console-logbook-server-container
    build:
      context: .
    restart: always
    ports:
      - 5000:5000
    networks: 
      - cslb-network
  web:
    image: docker.pkg.github.com/yarmsl/console.logbook/console-logbook-front
    container_name: console-logbook-front-container
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    networks: 
      - cslb-network
networks:
  cslb-network:
    driver: bridge